#!/usr/bin/ruby
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
def sum_even_fib(upper)
  fib1 = 1
  fib2 = 1
  result = 0
  summed = 0

  while result < upper
    summed += result if result.even?
    result = fib1 + fib2
    fib2 = fib1
    fib1 = result
  end
  summed
end

r = sum_even_fib(4000000)
puts r
