/*
 * Solution for Euler problem 002
 *
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
package org.tvarley.euler.solutions;

import org.tvarley.euler.Solution;

public class Solution002 implements Solution {
  public String solve() {
    int sum = 0;
    int fib1 = 1;
    int fib2 = 1;
    int running = 0;

    while( running < 4000000 ) {
      if( (running % 2) == 0 ) {
        sum += running;
      }
      running = fib1 + fib2;
      fib2 = fib1;
      fib1 = running;
    }
    return Integer.toString(sum);
  }
}
